### ISSUE TITLE
Best recruiters?

### ISSUE THREAD

**Issue by markgibaud** [tadast/switching-to-contracting-uk#25]
Please tell us a bit about your experience with a few recruitment agencies.

**Comment by Ricardo1980** [comment]
My only experience is with argyllscott (it's my first job as a contractor).
With them for 5 months.
At the moment no problems, the pay exactly 2 weeks after my client pays them.
Every time I have a question, they reply to my emails quickly.
Every 2 or 3 months, the recruiter comes close to the office and buys my a sandwich or similar and we talk 15 or 20 min. You know, networking.
Something I really like is that I send them the invoices generated automatically by Crunch, and I have some friends that cannot do that and they have to follow a template (something I guess is not legal, because a company should send its invoice using its own template)
