### ISSUE TITLE
IR35 law change

### ISSUE THREAD

**Issue by vdmtrv** [tadast/switching-to-contracting-uk#33]
What is everyone's opinion on the IR35 law changes that will take effect from 6th April 2020? Could this possibly be the death of contracting?

Reference: https://www.crunch.co.uk/knowledge/tax/changes-to-off-payroll-working-ir35-rules-effective-from-april-2020/

**Comment by tadast** [comment]
There is going to be some turbulence in April for sure, but it shouldn't have massive long term implications in my opinion. Best you can do to prepare personally:

- educate your current client about what's required for April changes to ensure you're outside IR35
- get your contract  IR35-reviewed if needed, so that adjustments can be made
- start talking to your contractor friends to see which clients are doing preparations and hire outside IR35, so you have a plan B ;)
- consider doing some work for public sector companies - there the change has been implemented for a couple of years, so there's a lot more up-front clarity of what you're getting into.

If the current client does not collaborate, increase your daily rate to cover your increased tax costs or simply run. If you can afford it, take a long break until things settle or accept a temporary financial hit on a daily rate.

Some useful references/info:
- status determination is something your clients will need to issue you before 6th April https://www.rjp.co.uk/ir35-update-understanding-the-sds-status-determination-statement/
- if you don't have the above after 6th April, you're inside IR35 by default and the deadline applies to invoice payments, not work performed
-  https://www.gov.uk/guidance/check-employment-status-for-tax and https://crunch.ir35.io/contractor-assessment/0
- https://www.qdoscontractor.com/ir35-contract-assessment - IR35 contract reviews

**Comment by lpil** [comment]
Lots of larger organisations are blanket deciding that all their contractors are inside IR35 and mandating use of umbrella companies, so if you work for larger companies you may be forced to re-jig some things.

**Comment by dideler** [comment]
FYI, [IR35 has been deferred until April 2021](https://www.cityam.com/ir35-reforms-to-be-delayed-for-a-year-due-to-coronavirus/). HMRC announced the 12-month delay on March 17 as part of government measures to support the economy through the COVID-19 pandemic.

**Comment by Ron-Maoz** [comment]
> What is everyone's opinion on the IR35 law changes that will take effect from 6th April 2020? Could this possibly be the death of contracting?
> 

I don't think IR35 has heralded the death of the contracting industry, but it definitely shrank it in 2020/21.
Long term, large corporations which have implemented an Inside IR35 blanket might need to adjust their policy and allow outside IR35 contracts for IT and tech talents.
I think that once the [old myths about IR35 are cleared out of the way](https://cleveraccounts.com/blog/ir35/what-makes-a-contract-outside-or-inside-ir35) we'll get better clarity in regards to do's and don'ts.
